version: '3.8'

services:
  logmind-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logmind_engine
    ports:
      - "8080:8080"
    volumes:
      - logmind_data:/app/data
    environment:
      - GO_ENV=production
      # To ensure the DB writes into our persistent volume, change the DB path in main.go to ./data/logmind.db
    restart: always

volumes:
  logmind_data:
    driver: local