services:
  logmind-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logmind_engine
    ports:
      - "8080:8080"
    volumes:
      - logmind_data:/app/data
    environment:
      - GO_ENV=production
    restart: always

volumes:
  logmind_data:
    driver: local